name: vertex_ai_planner
description: "Firebase Vertex AI Planner Sample"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_vertexai: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  all_lint_rules_community: ^0.0.43

flutter:
  uses-material-design: true
